# Local overrides for development
version: '3.7'

services:
  app:
    # entrypoint: /bin/bash
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: gltf_hub
    volumes:
      - .:/app:rw
      - app-user:/home/appuser
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gltf_hub
    ports:
      - 5434:5432
    volumes:
      # NOTE: only specifying it explicitly to make it a 'named' volume
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  # mainly to save bash history
  app-user:
